### ISSUE TITLE
Step 4 Error

### ISSUE THREAD

**Issue by reykajayasinghe** [huBioinfo/CytoTalk#10]
Hello - I am testing out the tool with the provided scRNAseq test data in the input folder- and am running into this below issue. 

Thanks for providing this tool!

[1] "(4/7) Constructing the integrated gene network...(around 40 min and need 10G space)"
[1] "------Calculating relevance coefficients for genes in cell type A..."
Error in Wnorm_TypA %*% Relevance_TypA : non-conformable arguments
Calls: constructIntegratedNetwork -> compNodePrize_RWR -> genRelevanceTypeA
In addition: Warning messages:
1: In cbind(geneMatrix, Exp_tpmMean[[i]]) :
  number of rows of result is not a multiple of vector length (arg 2)
2: In cbind(geneMatrix, Exp_tpmMean[[i]]) :
  number of rows of result is not a multiple of vector length (arg 2)
Execution halted

**Comment by huBioinfo** [comment]
> Hello - I am testing out the tool with the provided scRNAseq test data in the input folder- and am running into this below issue.
> 
> Thanks for providing this tool!
> 
> [1] "(4/7) Constructing the integrated gene network...(around 40 min and need 10G space)"
> [1] "------Calculating relevance coefficients for genes in cell type A..."
> Error in Wnorm_TypA %*% Relevance_TypA : non-conformable arguments
> Calls: constructIntegratedNetwork -> compNodePrize_RWR -> genRelevanceTypeA
> In addition: Warning messages:
> 1: In cbind(geneMatrix, Exp_tpmMean[[i]]) :
> number of rows of result is not a multiple of vector length (arg 2)
> 2: In cbind(geneMatrix, Exp_tpmMean[[i]]) :
> number of rows of result is not a multiple of vector length (arg 2)
> Execution halted

Dear User,

I've tested the software again using the provided data in the Input/ folder. No error occured. If the problem still exists, could you send me your generated /Ouput/ folder (a zip compressed file) at huyuxuan@xidian.edu.cn? I'll look into this problem. Maybe something wrong with some intermediate results generated before this step.
