### ISSUE TITLE
VROOM_WRITE_BUFFER_LINES error

### ISSUE THREAD

**Issue by sailseem** [huBioinfo/CytoTalk#15]
Dear,
    I have been using cytotalk for a really long time since its first release, it's a great package. Well, I just checked out the latest release and got an error like this,
> CytoTalk::run_cytotalk(type_a, type_b, dir_in,proteins = CytoTalk::pcg_mouse,
+                        ligands = CytoTalk::ligands_mouse)
[1 / 7] (09:39:04) Preprocessing...
[2 / 7] (09:39:48) Mutual information matrix...
[3 / 7] (11:48:42) Indirect edge-filtered network...
[4 / 7] (11:53:38) Integrate network...
[5 / 7] (12:01:39) PCSF...
Error in Sys.getenv("VROOM_WRITE_BUFFER_LINES", nrow(x)/100/num_threads) : 
  wrong type for argument

Can you help me with it? Thanks a lot.
BTW, I have a liite bit trouble in installation as well. 

> devtools::install_github("tanlabcode/CytoTalk", build_vignettes = TRUE)
Downloading GitHub repo tanlabcode/CytoTalk@HEAD
✓  checking for file ‘/private/var/folders/by/2dc9qylx40d5f6kfx153psxw0000gn/T/Rtmp3Dg1Ad/remotesba295063d4eb/tanlabcode-CytoTalk-64cb117/DESCRIPTION’ ...
─  preparing ‘CytoTalk’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (3.1s)
   --- re-building ‘cytotalk_guide.Rmd’ using rmarkdown
   pandoc: /Users/Shane/Code/packaging/CytoTalk/docs/CytoTalk_schematic.png: openBinaryFile: does not exist (No such file or directory)
   Error: processing vignette 'cytotalk_guide.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 1
   --- failed re-building ‘cytotalk_guide.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘cytotalk_guide.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'CytoTalk' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> pandoc: /Users/Shane/Code/packaging/CytoTalk/docs/CytoTalk_schematic.png: openBinaryFile: does not exist (No such file or directory)
E> Error: processing vignette 'cytotalk_guide.Rmd' failed with diagnostics:
E> pandoc document conversion failed with error 1
E> --- failed re-building ‘cytotalk_guide.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘cytotalk_guide.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted

but when I deleted " build_vignettes = TRUE" this argument, the installation works fine. I am not sure if this related to the above error at step 5/7. Thanks, again

**Comment by shanedrabing** [comment]
For the installation error, see this thread:

Seems like this should be a fix:

```console
devtools::install_github('rstudio/rmarkdown')
```

Now, as for the `vroom` error, I remember seeing something like that, but have forgotten the context. Can you screenshot your "CytoTalk-output" folder so I can see what files finished, make sure to include the file sizes. If you see any empty files, that could be an issue.

You can always restart your R session and try running CytoTalk again, it will pick up where it left off.

**Comment by sailseem** [comment]
Yes,sure,looks like this
![image](https://user-images.githubusercontent.com/72428172/137346383-bed76f16-d8b0-44c4-9a83-81d693b9cf8a.png)
Thanks,Shane

**Comment by shanedrabing** [comment]
Perfect, thank you! Notice the file "PCSF_NodeOccurance.txt"? This is likely what was written, just before the program had an error. It's file size is very small, so I'm thinking something must have happened to the PCST output. Try opening it up and see if it contains anything! I'm thinking perhaps no edges were found in the resultant network and that's where the error is coming from...

Here's what I can do for you, if you can send me the "IntegratedNetwork.cfg" file (you could try file.io), that's all I'll need to run the PCST step on my end and try fixing that bug.

**Comment by sailseem** [comment]
https://file.io/SgQ29UoJAUEi      Never used file io before, sorry for that, please try this. Well, all the value I set as default cutoff. Maybe my celltypes are so similar? BTW, yuxuan told me that I need more than 2 cell types in the folder even though I only check two specific cell interaction. Still works that way now?

**Comment by shanedrabing** [comment]
First time using file.io for myself as well!

If you look at that .cfg file, which is just a special filetype for input into the PCST, notice that all the values for prizes and costs are NA or NaN. I've never seen that before. It works same as before where you should have 2 or more cell types from your tissue sample. How large is your original data that you're inputting?

If you feel comfortable with it, you could zip up the two files you're using as input and I'll take a look.

**Comment by sailseem** [comment]
totally ok with that, please take a look   https://file.io/IAeiz30dezxe   Thanks, again!!!

**Comment by huBioinfo** [comment]
Hi, may be this thread can help. https://github.com/huBioinfo/CytoTalk/issues/11
They also generated NAs in edge cost and node prize parts and fixed this issue by cleaning unnecessary files in the Input folder to make sure the folder only contains **ln-transformed** gene expression matrix files (.csv) for **ALL** cell types in the tissue microenvironment. No other .csv files in it.

**Comment by sailseem** [comment]
All right, i will try that later, thanks, both of you guys!!!

**Comment by shanedrabing** [comment]
@sailseem I know it's been a while since I last took a look at this issue, but I was curious if you were still running into difficulties. You might want to check out CytoTalk on the `tanlabcode` fork, it's been improved a lot since this issue was created.

**Comment by sailseem** [comment]
well, thanks for reaching out, well i don't have any running difficulties so far. It has been great
