### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 117999** [huBioinfo/CytoTalk#17]
Hi, Dr Hu, 
We have tried to install the latest package from the manual you've uploaded on Github 'https://github.com/tanlabcode/CytoTalk'. However, it reported that the Cytotalk required an R version>4.1.0, which could be conflict with the python 3.7 for the dependencies PCST. Therefore, I am wondering what's the exact R/Python environment requirement for Cytotalk? 

I have issued the question on github and send emails to Prof.Tan but received no response
Thanks

**Comment by huBioinfo** [comment]
Hi Yuchen, 

I used the R version 4.1.3  and Python version 3.7.3 to install the latest CytoTalk R package and it works fine. Can you try these environments and let me know whether it works. Thanks!

**Comment by huBioinfo** [comment]
Hi Yuchen, 

I just tried the R version 4.1.3 and Python version 3.7.3 to install the CytoTalk R package. It works fine and can generate final results. Could you try these environments, thanks.

**Comment by 117999** [comment]
Hi Dr.Hu,
 I have tried to create a new environment with R=4.1.3 and python=3.7.3
`conda create -n rpy7 r-base=4.1.3 r-essentials python=3.7.3`
however, it reported the conflicts with libffi
`Found conflicts! Looking for incompatible packages.                                                                                                            failed                                                                                                                                                                                                                                                                                                                              
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                  
Package libffi conflicts for:
python=3.7.3 -> pip -> setuptools -> pypy3.7[version='>=7.3.7'] -> libffi[version='>=3.3,<3.4.0a0|>=3.4.2,<3.5.0a0']
python=3.7.3 -> libffi[version='>=3.2.1,<3.3.0a0|>=3.2.1,<3.3a0']
r-base=4.1.3 -> libglib[version='>=2.70.2,<3.0a0'] -> libffi[version='>=3.4.2,<3.5.0a0']
r-essentials -> mro-base[version='>=3.5.0'] -> glib[version='>=2.56.1,<3.0a0'] -> libffi[version='3.2.*|<3.3.0.a0|>=3.0.0|>=3.2.1|>=3.2.1,<3.3.0a0|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.4.2,<3.5.0a0']`

**Comment by huBioinfo** [comment]
Hi Yuchen,

I would recommend to use Rstudio to install and run the CytoTalk since the most of the coding part of this latest package is based on R. I also met some problems when using R under the conda environment previously. So you can first install the pcst_fast module using the "pip3" command and then install the CytoTalk package under the Rstudio environment using "devtools". That problem will no longer exist.

**Comment by huBioinfo** [comment]
Hi Yuchen,

Please see our new branch (https://github.com/tanlabcode/CytoTalk/tree/feature_RcallPy) to install the CytoTalk package and its dependencies completely in the R console for both Windows and macOS users.
