### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by 117999** [huBioinfo/CytoTalk#18]
Hi Dr.Hu,

We have also noticed that the description for visualizing pathway graphs with DiagrammeR and the Cytospace are vague. I am wondering how to process this once I have got the results$pathwat$graphs?

Thanks
Yuchen

**Comment by huBioinfo** [comment]
Hi Yuchen, 

I would recommend to specify the output folder when running the CytoTalk. For example, 
```
results <- CytoTalk::run_cytotalk(lst_scrna, type_a, type_b, dir_out = "./CytoTalk_Output")
```
In this way, you can get a "cytoscape" folder under the /CytoTalk_Output/ directory, which includes three files below ready for importing into the Cytoscape software for illustration.
(1) "CytoscapeNetwork.sif" is for showing the topology of the predicted network.
(2) "CytoscapeNodes.txt" is for showing the node attributes (e.g. cell type, node prize, or cell-type-spcificity score (PEM score)).
(3) "CytoscapeEdges.txt" is for showing the edge attributes (e.g. edge cost or edge type).

**Comment by KaKaPan2022** [comment]
Hi Dr.Hu,
We have tried to include the dir_out argument in the command.
However, upon the execution, no folders were found in the dir_out
instead, we received the following errors:
`Error in viewer(index_html) : 
  'browser' must be a non-empty character string
In addition: There were 50 or more warnings (use warnings() to see the first 50)`
we also checked the warnings and found that
`> warnings()
Warning messages:
1: In stats::ks.test(x, "pgamma", shape = shape, scale = scale) :
  ties should not be present for the Kolmogorov-Smirnov test`

**Comment by huBioinfo** [comment]
> Hi Dr.Hu, We have tried to include the dir_out argument in the command. However, upon the execution, no folders were found in the dir_out instead, we received the following errors: `Error in viewer(index_html) : 'browser' must be a non-empty character string In addition: There were 50 or more warnings (use warnings() to see the first 50)` we also checked the warnings and found that `> warnings() Warning messages: 1: In stats::ks.test(x, "pgamma", shape = shape, scale = scale) : ties should not be present for the Kolmogorov-Smirnov test`

Hi,

I'm sorry I cannot reproduce your error "Error in viewer(index_html)". Those warnings are ok and not related to the error. Do you use the Rstudio or the Conda? I would recommend to use Rstudio since it seems there exist some problems in the installation using Conda (see https://github.com/huBioinfo/CytoTalk/issues/17)
