### ISSUE TITLE
Error in compNodePrize_Combine(OutputPath) : can not find object 'TypA_ind'

### ISSUE THREAD

**Issue by JimmyLuo-WJ** [huBioinfo/CytoTalk#2]
Dear developer,
Cytotalk version 3.0.1 is really friendly to use and I have tried it to analyze my scRNA-seq data. But I got an error and have no idea how to deal with the problem. Could you help me with? Thank you very much.
<img width="864" alt="截圖 2021-05-15 下午7 34 37" src="https://user-images.githubusercontent.com/84230270/118359155-c04dd880-b5b4-11eb-9d9c-56f480c02cca.png">

**Comment by huBioinfo** [comment]
Dear Jimmy,
Thanks for your usage of CytoTalk 3.0.1 and reporting your issues. For your case, I think it's probably because your specified input parameter "CellTypeA" is not consistent to the naming of your input files "scRNAseq_xxx.csv". For example, if your "CellTypeA" is defined as "**Fibroblasts**", your input scRNA-seq data file should be named as "scRNAseq_**Fibroblasts**.csv". In this way, the intermediate parameter "TypA_ind" should then have a value. The consistent naming for "CellTypeB" should be also guaranteed. Please let me know if this problem can be addressed using this way. Thanks!

**Comment by JimmyLuo-WJ** [comment]
Dear developer,
My problem can truly be addressed by using this way! Thank you very much. I do input the file with wrong name which is no consistent to the parameter "CellTypeA". I just checked it and the error did not happen again. But when generating the final signaling network at step 6, another error occurs: "Subscript out of bounds" (or Subscript out of range). I have no idea what's going on.
<img width="685" alt="截圖 2021-05-16 下午2 43 01" src="https://user-images.githubusercontent.com/84230270/118388220-b4feb980-b655-11eb-931b-a8eb15f27cab.png">

**Comment by huBioinfo** [comment]
Dear Jimmy,
Can you give me a screenshot for the generated files (sorted by modified time) in the /Output/ folder, which could give me a clue for this issue. Thanks!

**Comment by JimmyLuo-WJ** [comment]
Dear developer,
No problem. Here are generated files in my output folder.
<img width="708" alt="截圖 2021-05-16 下午11 36 11" src="https://user-images.githubusercontent.com/84230270/118403156-aa691200-b69f-11eb-818a-d844be98db66.png">
<img width="712" alt="截圖 2021-05-16 下午11 36 27" src="https://user-images.githubusercontent.com/84230270/118403159-afc65c80-b69f-11eb-9d86-15a530f3c4d9.png">
<img width="711" alt="截圖 2021-05-16 下午11 36 38" src="https://user-images.githubusercontent.com/84230270/118403164-b3f27a00-b69f-11eb-9801-5881e9a1af3e.png">
<img width="713" alt="截圖 2021-05-16 下午11 36 47" src="https://user-images.githubusercontent.com/84230270/118403166-b7860100-b69f-11eb-96a8-bc35f00d97f9.png">

**Comment by huBioinfo** [comment]
Hi Jimmy, 
Sorry for the late reply. Do you have 100 subfolders (with prefix "bt") under your /Output/ folder? If so, I'm also confused with this problem. If it's convenient for you, can you share the /Output/ folder with me via some tools and I'll look into this problem. The /Output/ folder does not include any raw data, just intermediate results. Looking forward to your reply. Thanks!

**Comment by JimmyLuo-WJ** [comment]
Dear developer,

This problem also confused me. I uploaded my output files to the google drive and the link is as below. Please check it. Thanks.

https://drive.google.com/drive/folders/1-XmPXP3Qv-CwyMI3kYwqfTvbx7Vhjftg?usp=sharing

 

羅偉嘉 Wei-Jia Luo
Ph.D student
Tel: +886-2-2312-3456 ext 66923

Department of Clinical Laboratory Sciences and Medical Biotechnology, College of Medicine, National Taiwan University.
Rm. 521-1, 5F., No.1, Changde St., Zhongzheng Dist., Taipei City 100, Taiwan (R.O.C.).

 

寄件者: huBioinfo ***@***.***>
回覆: huBioinfo/CytoTalk ***@***.***>
日期: 2021年5月17日 星期一 下午5:46
收件者: huBioinfo/CytoTalk ***@***.***>
副本: JimmyLuo-WJ ***@***.***>, Author ***@***.***>
主旨: Re: [huBioinfo/CytoTalk] Error in compNodePrize_Combine(OutputPath) : can not find object 'TypA_ind' (#2)

 

Hi Jimmy,
Sorry for the late reply. Do you have 100 subfolders (with prefix "bt") under your /Output/ folder? If so, I'm also confused with this problem. If it's convenient for you, can you share the /Output/ folder with me via some tools and I'll look into this problem. The /Output/ folder does not include any raw data, just intermediate results. Looking forward to your reply. Thanks!

**Comment by JimmyLuo-WJ** [comment]
Dear developer,
Sure. I just upload my output files to google drives and send the link to your mail address. Please check it.

**Comment by huBioinfo** [comment]
Dear Jimmy, 
I'm downloading it. Will try to give you feedback soon. Thanks!

**Comment by huBioinfo** [comment]
Dear Jimmy,

I've found the problem and fixed it by revising the script "deter_W4.R" under the /Input/ folder in the latest package "**CytoTalk_package_v3.0.2**". Please download it from https://github.com/huBioinfo/CytoTalk/releases/tag/v3.0.2
Thank you so much for making an important contribution to improving this package!!! Hope everything goes well with the latest one.

**Comment by JimmyLuo-WJ** [comment]
Dear developer,

I have downloaded the latest version of Cytotalk (v3.0.2) and my data went well with it. The output folder /IllustratePCSF/ was successfully generated. Thank you very much for helping me.
