### ISSUE TITLE
Possible issue with python package 'pcst_fast'

### ISSUE THREAD

**Issue by rme2023-28** [huBioinfo/CytoTalk#20]
Hello,

I am quite fond of using CytoTalk but at of late I have been running into an issue when the program goes to interface with Python and use the 'pcst_fast' package. I am only a year into working with bioinformatics, so this could very well be a user error issue, but it's something I've been failing at troubleshooting nonetheless.

It processes through step 4/8 and fails at the PCSF step. The output I get is the following:

[1 / 8] (09:22:54) Preprocessing...
[2 / 8] (09:23:18) Mutual information matrix...
[3 / 8] (09:25:23) Indirect edge-filtered network...
[4 / 8] (09:25:24) Integrate network...
[5 / 8] (09:25:30) PCSF...
Error in py_get_attr(x, name, FALSE) : 
  AttributeError: module 'pcst_fast' has no attribute 'pcst_fast'
Run `reticulate::py_last_error()` for details.
Calls: <Anonymous> ... run_pcst -> $ -> $.python.builtin.module -> py_get_attr
Execution halted

I am working in an HPC cluster and the loadable python version that I am using is 3.8. I encode it in my script to list out the pcst_fast version during a run and it is able to list version 1.0.10, which I believe is the most recent version. Any help would be greatly appreciated. If you have any further questions please let me know.

Thank you for your time!
-A grad student in need of some help

**Comment by huBioinfo** [comment]
Hi,

Thanks for your interest in CytoTalk. This error is probably related with incorrect installation of the pcst_fast python module. Did you install the CytoTalk package according to the "feature_RcallPy" branch of the "tanlabcode/CytoTalk" repository (https://github.com/tanlabcode/CytoTalk/tree/feature_RcallPy). If not, please use my just updated installation procedures in that branch. I tested it and everything seems fine. Please let me know if you still get errors. Thanks!

**Comment by rme2023-28** [comment]
Hi,
This solved my issue! Thank you for your time!
-A now very happy graduate student :)
