### ISSUE TITLE
Error in install pcst_fast

### ISSUE THREAD

**Issue by JiangyanYu** [huBioinfo/CytoTalk#3]
Dear developer,

Thanks for sharing the latest version! It helps a lot to avoid using Matlab in docker.

Unfortunately I have problems to install pcst_fast module on my linux docker (Ubuntu 20.04.2). I used the pip3 option. Have you ever tested the package on the Ubuntu V20.04?

Thanks very much! Looking forward to hearing from you!

Best, Jiangyan

**Comment by huBioinfo** [comment]
Dear Jiangyan,

Thanks for supporting CytoTalk. I've tested it on Ubuntu 20.04 and using pip3 command indeed doesn't work. I have updated the manual of V3.0.2 by adding an alternative way to install pcst_fast module (Python3) according to https://github.com/fraenkel-lab/pcst_fast    You can either redownload the "CytoTalk_package_v3.0.2.zip" from https://github.com/huBioinfo/CytoTalk/releases/tag/v3.0.2 and find the updated manual or directly download it here.
[UserManual_v3.0.2.pdf](https://github.com/huBioinfo/CytoTalk/files/6534698/UserManual_v3.0.2.pdf). Please let me know any further questions. Thanks!

**Comment by JiangyanYu** [comment]
Thanks! This solved my problem perfectly! 

Best, Jiangyan
