### ISSUE TITLE
error when computing mutual information

### ISSUE THREAD

**Issue by lxcfuji** [huBioinfo/CytoTalk#8]
Hi Hu,

I'm having error when running step 2, please see below. could you please help me with it?

[1] "(2/7) Computing mutual information for cell type A...(around 2 hours)"
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Error in { : 
  task 1 failed - "task 1 failed - "supply both 'X' and 'Y' or a matrix-like 'X'""
Calls: compMI_TypeA -> %dopar% -> <Anonymous>
Execution halted

**Comment by huBioinfo** [comment]
Dear User,

It's also a new error to me. Seems like something wrong with the data import. I probably need more information to figure it out. Could you send me your currently generated **Output/** folder to me at "huyuxuan@xidian.edu.cn" or "yuxuan_hu_xd@163.com"? Thanks.

**Comment by GouQiao** [comment]
Hi Hu,

I also had error when running step 2.  [compMI_TypeA(OutputPath)]

[1] "(2/7) Computing mutual information for cell type A...(around 2 hours)"
Error in makeForkCluster(nnodes = spec, ...) : Cluster setup failed.
In addition: Warning message:
In socketAccept(socket = socket, blocking = TRUE, open = "a+b",  :
  problem in accepting connections on this socket
Called from: makeForkCluster(nnodes = spec, ...)

Do you know how can I overcome this problem?

**Comment by huBioinfo** [comment]
> Hi Hu,
> 
> I also had error when running step 2. [compMI_TypeA(OutputPath)]
> 
> [1] "(2/7) Computing mutual information for cell type A...(around 2 hours)"
> Error in makeForkCluster(nnodes = spec, ...) : Cluster setup failed.
> In addition: Warning message:
> In socketAccept(socket = socket, blocking = TRUE, open = "a+b", :
> problem in accepting connections on this socket
> Called from: makeForkCluster(nnodes = spec, ...)
> 
> Do you know how can I overcome this problem?

Hi Qiao,

I think it's probably because there might be some difference in the "makeCluster" function usage between Unix-based system and Windows. Please try this way. Replace the code at Line 17 of the script "comp_MIcoexp_TypA_WinPara.R" and "comp_MIcoexp_TypB_WinPara.R" in the /CytoTalk_Function/ folder by **cl <- makeCluster(no_cores)**. That is just delete the "type" parameter. Please let me know if this doesn't work.

**Comment by GouQiao** [comment]
> > Hi Hu,
> > I also had error when running step 2. [compMI_TypeA(OutputPath)]
> > [1] "(2/7) Computing mutual information for cell type A...(around 2 hours)"
> > Error in makeForkCluster(nnodes = spec, ...) : Cluster setup failed.
> > In addition: Warning message:
> > In socketAccept(socket = socket, blocking = TRUE, open = "a+b", :
> > problem in accepting connections on this socket
> > Called from: makeForkCluster(nnodes = spec, ...)
> > Do you know how can I overcome this problem?
> 
> Hi Qiao,
> 
> I think it's probably because there might be some difference in the "makeCluster" function usage between Unix-based system and Windows. Please try this way. Replace the code at Line 17 of the script "comp_MIcoexp_TypA_WinPara.R" and "comp_MIcoexp_TypB_WinPara.R" in the /CytoTalk_Function/ folder by **cl <- makeCluster(no_cores)**. That is just delete the "type" parameter. Please let me know if this doesn't work.

Thank you so much! It worked!
